module.exports = [
    // {name: '', pNumber: '', eAddress: '', title: '',},
    {name: 'Test Testerson', pNumber: '1234567890', eAddress: 'testerson@manager.com', title: 'Test'},
    {name: 'Jack Atlas', pNumber: '0987654321', eAddress: 'atlas@manager.com', title: 'Adventurer'},
    // {name: 'Monkey D Luffy', pNumber: '9999999999', eAddress: 'pirate@manager.com', title: 'King of the Pirates'},
    // {name: 'Luke Skywalker', pNumber: '8888888888', eAddress: 'jedi@manager.com', title: 'Jedi Master'},
    // {name: 'Tony Stark', pNumber: '7777777777', eAddress: 'ironman@manager.com', title: 'Iron Man'},
    // {name: 'Clark Kent', pNumber: '6666666666', eAddress: 'superman@manager.com', title: 'Superman'},
    // {name: 'Peter Parker', pNumber: '5555555555', eAddress: 'spiderman@manager.com', title: 'Spiderman'},
    // {name: 'Steve Rodgers', pNumber: '4444444444', eAddress: 'captain@manager.com', title: 'Captain America'},
    // {name: 'Bruce Wayne', pNumber: '3333333333', eAddress: 'batman@manager.com', title: 'Batman'},
    // {name: 'Bruce Banner', pNumber: '2222222222', eAddress: 'hulk@manager.com', title: 'Hulk'},
    // {name: 'Barry Allen', pNumber: '1212121212', eAddress: 'flash@manager.com', title: 'The Flash'},
    // {name: 'Reed Richards', pNumber: '1357924680', eAddress: 'fantastic@manager.com', title: 'Mr. Fantastic'},
    // {name: 'Hal Jordan', pNumber: '0864297531', eAddress: 'greenlantern@manager.com', title: 'Green Lantern'},
    // {name: 'Wade Wilson', pNumber: '5554443333', eAddress: 'deadpool@manager.com', title: 'Deadpool'},
    // {name: 'Dick Grayson', pNumber: '0009998888', eAddress: 'robin@manager.com', title: 'Robin'},
    // {name: 'Scott Summers', pNumber: '9998887777', eAddress: 'cyclops@manager.com', title: 'Cyclops'},
    // {name: 'Stephen Strange', pNumber: '8887776666', eAddress: 'drstrange@manager.com', title: 'Doctor and Wizard'},
    // {name: 'Arthur Curry', pNumber: '7776665555', eAddress: 'aquaman@manager.com', title: 'Aquaman'},
]